# Change these first
owner: Team-Vegan-at # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Team Vegan.at WWW
    url: https://www.teamvegan.at
  - name: Team Vegan.at API
    url: https://api.teamvegan.at/ping
  - name: Team Vegan.at Membership Poratl
    url: https://mitgliedschaft.teamvegan.at
  - name: Team Vegan.at Forum
    url: https://mitglieder.teamvegan.at
  - name: Team Vegan.at WWW-QS
    url: https://www-qs.teamvegan.at
  - name: Team Vegan.at API-QS
    url: https://api-qs.teamvegan.at/ping

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.teamvegan.at
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Team Vegan.at
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
